import process from "node:process";

import { createEnv } from "@t3-oss/env-core";
import { isProduction } from "std-env";
import { z } from "zod";

console.debug("⏳ [ENV_SERVER] Loading environment variables...", {
  SOURCE_COMMIT: process.env.SOURCE_COMMIT,
  VITE_SERVER_URL: process.env.VITE_SERVER_URL,
  VITE_WEB_URL: process.env.VITE_WEB_URL
});

export const ENV_SERVER = createEnv({
  emptyStringAsUndefined: true,
  runtimeEnv: process.env,
  server: {
    VITE_SERVER_URL: isProduction ? z.url() : z.url().default("http://localhost:5000/server"),
    VITE_WEB_URL: isProduction ? z.url() : z.url().default("http://localhost:3000/web"),
    DATABASE_URL: z.string().min(1),
    BETTER_AUTH_SECRET: z.string().min(32),
    ROOT_BOOTSTRAP_EMAILS: z.string().default(""),
    RESEND_API_KEY: z.string().min(1).optional(),
    EMAIL_FROM: z.string().min(3).optional(),
    NODE_ENV: z.enum(["development", "production"]).default("development"),
    SOURCE_COMMIT: z.string().min(1).default("unknown"), // autogenerated by Coolify, needs to be manually set otherwise
    ENABLE_OPEN_API_DOCS: z.stringbool().default(false),
    IS_BUILD: z.stringbool().default(false) // set to 'true' during build, can be used to conditionally disable features that should only run during runtime and not during build/prerendering
  }
});

console.debug("✅ [ENV_SERVER] Successfully loaded environment variables.");
